version: '3.8'

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: modelpilot-proxy
    ports:
      - "${LITELLM_PORT:-4001}:4000"
    volumes:
      - ${CONFIG_PATH:-./config.yaml}:/app/config.yaml
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - STORE_MODEL_IN_DB=True
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: [ "--detailed_debug", "--port", "4000", "--config", "/app/config.yaml" ]
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15-alpine
    container_name: modelpilot-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH:-./postgres_data}:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: modelpilot-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ${REDIS_DATA_PATH:-./redis_data}:/data
    restart: always
